# Generated by Django 5.1.1 on 2024-10-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='pickup_date',
            field=models.DateField(),
        ),
    ]
