# Generated by Django 5.1.1 on 2024-10-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_clientdata_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='client_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='customization',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
