# Generated by Django 5.1.1 on 2024-10-25 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_alter_clientdata_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='client_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='customization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
