# Generated by Django 5.1.1 on 2024-10-25 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_alter_clientdata_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='client_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
