# Generated by Django 5.1.1 on 2024-11-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_clientdata_recommended_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.CharField(max_length=255)),
                ('order_type', models.CharField(max_length=255)),
                ('customization', models.CharField(max_length=255)),
                ('recommended_product', models.CharField(max_length=255)),
            ],
        ),
    ]
