# Generated by Django 5.1.1 on 2024-11-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_recommendationdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdata',
            old_name='order',
            new_name='orders',
        ),
    ]
